global:
  dist-dirs: &distDirs dist
  tsconfig: tsconfig.json

clean-pkg-json:
  sort-scripts: true

copy-files:
  from:
    - package.json
    - LICENSE
    - CHANGELOG.md
    - README.md
  to: *distDirs

build:
  entry: src/index.ts
  license-banner: true
  out: *distDirs
  umd-name: MyLib
  externals: tslib
