branch: master
tagFormat: '${version}'

verifyConditions:
  - path: &npm '@semantic-release/npm'
    pkgRoot: '.'
  - &gh '@semantic-release/github'

prepare:
  - '@semantic-release/changelog'
  - *npm
  - path: &exec '@semantic-release/exec'
    cmd: node sync-version.js
  - path: *exec
    cmd: 'npm run build'
  - path: '@semantic-release/git'
    message: 'chore(release): ${nextRelease.version}'
    assets:
      - CHANGELOG.md
      - README.md
      - package.json
      - projects/ngx-sails/package.json
      - package-lock.json

publish:
  - path: *exec
    cmd: bash -c "cd dist/ngx-sails && npm publish"
  - *gh

generateNotes:
  config: '@alorel-personal/conventional-changelog-alorel'
