language: node_js
node_js: stable
env:
  global:
    - COVERALLS_PARALLEL=true

before_install:
  - npm i -g yarn greenkeeper-lockfile
  - greenkeeper-lockfile-update
install: yarn install --check-files

script:
  - yarn run tslint
  - yarn test
  - yarn run build:demo:aot
  - if [[ $GH_TOKEN ]]; then semantic-release --dry-run; fi;

after_script: if [[ $GH_TOKEN ]]; then greenkeeper-lockfile-upload; fi;
after_success: cat ./coverage/lcov.info | coveralls

before_cache: rm -rf ./node_modules/.cache
cache:
  yarn: true

stages:
  - Test
  - name: Release
    if: branch = master AND type = push AND (NOT tag IS present)

jobs:
  include:
    - stage: Test
      os: linux
      addons:
        chrome: stable
        firefox: latest
    - stage: Release
      node_js: stable
      before_install: npm i -g yarn
      before_script:
        - yarn run build:lib
        - alo copy-files
      script: semantic-release
      after_success: []
      after_script: []

notifications:
  webhooks: https://coveralls.io/webhook
