name: Core
on:
  push:
    branches: [master]
  pull_request: {}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        uses: ./.github/actions/test
        with:
          node-version: 20
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Release dry run
        run: npm run release:dry
        env:
          GITHUB_TOKEN: ${{ github.token }}
          
      - name: Upload coverage
        if: ${{ runner.os != 'windows-latest' }}
        continue-on-error: true
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ inputs.node-version }}-on-${{ runner.os }}-${{ github.event_name }}
          path-to-lcov: ./coverage/ngx-sails/lcov.info
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1000
          persist-credentials: false
      - name: Init NPM
        uses: ./.github/actions/init-npm
        with:
          node-version: 20
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        name: Reconfig Node
        with:
          node-version: 20
          registry-url: https://registry.npmjs.org
      - name: Release
        run: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
