name: Core
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test ubuntu-latest/Node 18
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Test
        uses: ./.github/actions/test
        with:
          node-version: 18
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage
        if: ${{ runner.os != 'windows-latest' }}
        continue-on-error: true
        uses: coverallsapp/github-action@v2.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: node-${{ inputs.node-version }}-on-${{ runner.os }}-${{ github.event_name }}
          path-to-lcov: ./coverage/ngx-sails/lcov.info
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}
    needs:
      - test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1000
      - name: Init NPM
        uses: ./.github/actions/init-npm
        with:
          node-version: 18
          gh-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/setup-node@v3
        name: Reconfig Node
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org
      - name: Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
